-- Generated by Gemini CLI - Senior Database Architect
--
-- Target DB: Microsoft SQL Server 2022 Express
-- Database: [demo_utm_AGBM]
-- Objective: Create the core table structure for UTM_Market.

-- Best Practices: Ensure atomicity and reduce network traffic from informational messages.
SET NOCOUNT ON;
SET XACT_ABORT ON;

-- Ensure the script operates within the correct database context.
USE [demo_utm_AGBM];
GO

-- =================================================================================
-- Tabla: Producto
-- Almacena los artículos disponibles para la venta.
-- =================================================================================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Producto]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Producto] (
        [ProductoID]    INT IDENTITY(1,1) NOT NULL,
        [Nombre]        NVARCHAR(100) NOT NULL,
        [SKU]           VARCHAR(20) NOT NULL,
        [Marca]         NVARCHAR(50) NULL,
        [Precio]        DECIMAL(19,4) NOT NULL,
        [Stock]         INT NOT NULL,

        -- Constraints
        CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED ([ProductoID] ASC),
        CONSTRAINT [UQ_Producto_SKU] UNIQUE NONCLUSTERED ([SKU] ASC),
        CONSTRAINT [CHK_Producto_Precio] CHECK ([Precio] >= 0),
        CONSTRAINT [CHK_Producto_Stock] CHECK ([Stock] >= 0)
    );
END
GO

-- =================================================================================
-- Tabla: Venta
-- Registra cada transacción de venta única.
-- =================================================================================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Venta]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Venta] (
        [VentaID]       INT IDENTITY(1,1) NOT NULL,
        [Folio]         VARCHAR(20) NOT NULL,
        [FechaVenta]    DATETIME NOT NULL DEFAULT GETDATE(),
        [TotalArticulos] INT NOT NULL,
        [TotalVenta]    DECIMAL(19,4) NOT NULL,
        [Estatus]       TINYINT NOT NULL, -- 1: Pendiente, 2: Completada, 3: Cancelada

        -- Constraints
        CONSTRAINT [PK_Venta] PRIMARY KEY CLUSTERED ([VentaID] ASC),
        CONSTRAINT [UQ_Venta_Folio] UNIQUE NONCLUSTERED ([Folio] ASC),
        CONSTRAINT [CHK_Venta_Estatus] CHECK ([Estatus] IN (1, 2, 3)),
        CONSTRAINT [CHK_Venta_TotalArticulos] CHECK ([TotalArticulos] >= 0),
        CONSTRAINT [CHK_Venta_TotalVenta] CHECK ([TotalVenta] >= 0)
    );
END
GO

-- =================================================================================
-- Tabla: DetalleVenta
-- Almacena los productos específicos incluidos en cada venta.
-- =================================================================================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DetalleVenta]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[DetalleVenta] (
        [DetalleID]     INT IDENTITY(1,1) NOT NULL,
        [VentaID]       INT NOT NULL,
        [ProductoID]    INT NOT NULL,
        [PrecioUnitario] DECIMAL(19,4) NOT NULL,
        [Cantidad]      INT NOT NULL,
        [TotalDetalle]  DECIMAL(19,4) NOT NULL,

        -- Constraints
        CONSTRAINT [PK_DetalleVenta] PRIMARY KEY CLUSTERED ([DetalleID] ASC),
        CONSTRAINT [CHK_DetalleVenta_PrecioUnitario] CHECK ([PrecioUnitario] >= 0),
        CONSTRAINT [CHK_DetalleVenta_Cantidad] CHECK ([Cantidad] > 0)
    );
END
GO

-- =================================================================================
-- Relaciones (Foreign Keys)
-- Establecen la integridad referencial entre las tablas.
-- =================================================================================

-- Relación: Venta -> DetalleVenta (1:N)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DetalleVenta_Venta]') AND parent_object_id = OBJECT_ID(N'[dbo].[DetalleVenta]'))
BEGIN
    ALTER TABLE [dbo].[DetalleVenta] ADD CONSTRAINT [FK_DetalleVenta_Venta]
    FOREIGN KEY ([VentaID]) REFERENCES [dbo].[Venta] ([VentaID])
    ON DELETE CASCADE;
END
GO

-- Relación: Producto -> DetalleVenta (1:N)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DetalleVenta_Producto]') AND parent_object_id = OBJECT_ID(N'[dbo].[DetalleVenta]'))
BEGIN
    ALTER TABLE [dbo].[DetalleVenta] ADD CONSTRAINT [FK_DetalleVenta_Producto]
    FOREIGN KEY ([ProductoID]) REFERENCES [dbo].[Producto] ([ProductoID]);
END
GO
