-- Generated by Gemini CLI - Senior Database Architect (Corrected)
--
-- Target DB: Microsoft SQL Server 2022 Express
-- Database: [demo_utm_AGBM]
-- Objective: Seed the 'Producto' table with 250 high-rotation products for the Mexican market.

-- Best Practices: Ensure atomicity, idempotency, and error handling.
SET NOCOUNT ON;
SET XACT_ABORT ON;

-- Ensure the script operates within the correct database context.
USE [demo_utm_AGBM];
GO

BEGIN TRANSACTION;

BEGIN TRY
    -- 1. CLEANUP PHASE
    -- Use DELETE and RESEED to handle Foreign Key constraints.
    DELETE FROM [dbo].[Producto];
    DBCC CHECKIDENT ('[dbo].[Producto]', RESEED, 0);

    -- 2. DATA INSERTION PHASE
    -- Inserting 250 products.

    -- Batch 1/5: Refrescos, Botanas, Lácteos, Panadería (50 items)
    INSERT INTO [dbo].[Producto] ([Nombre], [SKU], [Marca], [Precio], [Stock]) VALUES
    (N'Coca-Cola Original 600ml', '7501055300078', N'Coca-Cola', 18.50, 210),
    (N'Sabritas Original 45g', '7501011115306', N'Sabritas', 17.00, 180),
    (N'Leche Lala Entera 1L', '7501020500019', N'Lala', 28.50, 90),
    (N'Gansito 50g', '7501000110452', N'Marinela', 18.00, 150),
    (N'Agua Ciel 1L', '7501055301372', N'Ciel', 14.00, 130),
    (N'Doritos Nacho 58g', '7500478004128', N'Sabritas', 17.50, 165),
    (N'Yogurt Fresa 125g', '7501020531013', N'Danone', 9.50, 110),
    (N'Pan Bimbo Blanco Grande', '7501000111114', N'Bimbo', 48.00, 70),
    (N'Atún Dolores en Agua 140g', '7501045400108', N'Dolores', 23.00, 85),
    (N'Jabón Zote Rosa 400g', '7501035900019', N'Zote', 25.50, 100),
    (N'Pepsi 600ml', '7501031311309', N'Pepsi', 17.50, 190),
    (N'Ruffles Queso 52g', '7501011105024', N'Sabritas', 17.00, 175),
    (N'Leche Alpura Clásica 1L', '7501055900017', N'Alpura', 27.50, 88),
    (N'Pingüinos 80g', '7501000110438', N'Marinela', 26.00, 140),
    (N'Jugo Jumex Naranja 1L', '7501013100017', N'Jumex', 29.00, 80),
    (N'Cheetos Torciditos 52g', '7501011115320', N'Sabritas', 16.50, 160),
    (N'Danonino Fresa 42g', '7501020510100', N'Danone', 7.00, 200),
    (N'Donas Bimbo Azucaradas 6pzas', '7501000112340', N'Bimbo', 32.00, 65),
    (N'Mayonesa McCormick Limón 190g', '7501003340626', N'McCormick', 30.00, 95),
    (N'Pasta Colgate Triple Acción 50ml', '7509546077596', N'Colgate', 22.00, 115),
    (N'Fanta Naranja 600ml', '7501055300092', N'Fanta', 17.00, 185),
    (N'Takis Fuego 62g', '7500478004388', N'Barcel', 17.00, 195),
    (N'Leche Santa Clara Entera 1L', '7503003020227', N'Santa Clara', 30.00, 80),
    (N'Chocoroles 3pzas', '7501000110469', N'Marinela', 27.50, 130),
    (N'Nescafé Clásico 42g', '7501058619161', N'Nescafé', 35.00, 75),
    (N'Shampoo Pantene Restauración 180ml', '7500435137277', N'Pantene', 38.00, 60),
    (N'Sprite 600ml', '7501055300115', N'Sprite', 17.50, 170),
    (N'Chips Jalapeño 50g', '7500478004142', N'Barcel', 16.50, 155),
    (N'Crema Lala Ácida 200ml', '7501020510018', N'Lala', 15.00, 105),
    (N'Mantecadas Vainilla 6pzas', '7501000112326', N'Bimbo', 25.00, 120),
    (N'Frijoles La Sierra Refritos 440g', '7501052470126', N'La Sierra', 19.50, 90),
    (N'Papel Higiénico Pétalo 4 rollos', '7501083296181', N'Pétalo', 35.00, 110),
    (N'Jarritos Tamarindo 600ml', '7501001001041', N'Jarritos', 16.00, 160),
    (N'Cacahuates Japonés 60g', '7501001210108', N'Nishikawa', 13.50, 200),
    (N'Yogurt Griego Fage 150g', '7503011358055', N'Fage', 35.00, 70),
    (N'Pan Tostado Clásico 210g', '7501000111428', N'Bimbo', 40.00, 60),
    (N'Sopa Maruchan Pollo 64g', '0070662087023', N'Maruchan', 16.50, 220),
    (N'Cloro Cloralex 950ml', '7501021100011', N'Cloralex', 24.00, 85),
    (N'Manzanita Sol 600ml', '7501031311323', N'Sol', 17.00, 150),
    (N'Churrumais 67g', '7501011115344', N'Sabritas', 16.00, 180),
    (N'Queso Panela Noche Buena 200g', '7501040000049', N'Noche Buena', 45.00, 55),
    (N'Submarinos Fresa 3pzas', '7501000110483', N'Marinela', 27.00, 125),
    (N'Café Legal Soluble 42g', '7501003411098', N'Legal', 32.00, 70),
    (N'Jabón de Tocador Palmolive Neutro Balance 150g', '7509546070627', N'Palmolive', 18.00, 140),
    (N'Red Bull Lata 250ml', '9002490206122', N'Red Bull', 45.00, 50),
    (N'Papas Toreadas Habanero 50g', '7500478004203', N'Barcel', 17.50, 140),
    (N'Yakult 5pzas', '7501020510063', N'Yakult', 35.00, 80),
    (N'Medias Noches 8pzas', '7501000111220', N'Bimbo', 38.00, 75),
    (N'Azúcar Zulka Morena 1kg', '7501022000018', N'Zulka', 38.00, 90),
    (N'Galletas de Animalitos 200g', '7501007500076', N'Gamesa', 14.00, 220);

    -- Batch 2/5: Abarrotes, Higiene, Refrescos (50 items)
    INSERT INTO [dbo].[Producto] ([Nombre], [SKU], [Marca], [Precio], [Stock]) VALUES
    (N'Aceite 1-2-3 Vegetal 1L', '7501003100014', N'1-2-3', 55.00, 65),
    (N'Rastrillo Gillette Prestobarba3 2pzas', '7500435133378', N'Gillette', 50.00, 70),
    (N'Gatorade Naranja 500ml', '7501059242017', N'Gatorade', 25.50, 110),
    (N'Rancheritos 58g', '7501011115382', N'Sabritas', 17.00, 170),
    (N'Leche Nido Kinder 400g', '7501058619611', N'Nestlé', 90.00, 40),
    (N'Bimbollos 8pzas', '7501000111213', N'Bimbo', 38.00, 80),
    (N'Salsa Valentina Etiqueta Amarilla 370ml', '7501053900016', N'Valentina', 16.00, 130),
    (N'Fabuloso Lavanda 1L', '7509546050735', N'Fabuloso', 28.00, 90),
    (N'Boing Guayaba 500ml', '7501001000044', N'Pascual', 15.00, 120),
    (N'Fritos Sal y Limón 57g', '7501011115405', N'Sabritas', 16.50, 160),
    (N'Margarina Primavera con Sal 90g', '7501024200013', N'Primavera', 18.00, 85),
    (N'Pan Dulce Donas 4pzas', '7501000112357', N'Bimbo', 28.00, 95),
    (N'Arroz Verde Valle 1kg', '7501062110010', N'Verde Valle', 34.00, 75),
    (N'Toallas Femeninas Always Ultra Fina 10pzas', '7500435136539', N'Always', 40.00, 60),
    (N'Powerade Moras 500ml', '7501055301396', N'Powerade', 25.00, 105),
    (N'Cheetos Poffs 48g', '7501011115368', N'Sabritas', 16.50, 150),
    (N'Philadelphia Queso Crema 190g', '7501001410011', N'Philadelphia', 42.00, 65),
    (N'Barritas Fresa 2pzas', '7501000110506', N'Marinela', 16.00, 180),
    (N'Lentejas Verde Valle 500g', '7501062120019', N'Verde Valle', 25.00, 70),
    (N'Desodorante Axe Chocolate 150ml', '7506195000015', N'Axe', 65.00, 55),
    (N'Delaware Punch 600ml', '7501055300139', N'Delaware', 16.50, 140),
    (N'Tostitos Salsa Verde 65g', '7501011115429', N'Tostitos', 17.50, 165),
    (N'Yogurt bebible Lala Fresa 220g', '7501020510162', N'Lala', 12.00, 150),
    (N'Roles de Canela con Pasas 2pzas', '7501000112425', N'Bimbo', 29.00, 80),
    (N'Mostaza French''s 226g', '0041500000300', N'French''s', 35.00, 60),
    (N'Acondicionador Sedal Restauración 190ml', '7506306210034', N'Sedal', 40.00, 65),
    (N'Sangría Señorial 600ml', '7501007500021', N'Señorial', 18.00, 130),
    (N'Popkaramel 60g', '7500478004401', N'Barcel', 16.00, 145),
    (N'Mantequilla Gloria con Sal 90g', '7501040000018', N'Gloria', 25.00, 80),
    (N'Panqué con Pasas 255g', '7501000112401', N'Bimbo', 36.00, 70),
    (N'Puré de Tomate Del Fuerte 210g', '7501017000015', N'Del Fuerte', 8.50, 200),
    (N'Talco para pies Mexana 150g', '7501053300018', N'Mexana', 55.00, 50),
    (N'Coca-Cola Sin Azúcar 600ml', '7501055301778', N'Coca-Cola', 18.00, 150),
    (N'Chicharrones de Cerdo 50g', '7501011115443', N'Sabritas', 20.00, 130),
    (N'Activia Ciruela Pasa 125g', '7501020531068', N'Danone', 10.50, 140),
    (N'Pan Integral Grande', '7501000111138', N'Bimbo', 52.00, 60),
    (N'Chiles La Costeña Rajitas 220g', '7501017000053', N'La Costeña', 15.00, 120),
    (N'Crema Corporal Nivea Milk Nutritiva 250ml', '4005808821430', N'Nivea', 58.00, 65),
    (N'Peñafiel Agua Mineral 600ml', '7501073840049', N'Peñafiel', 15.00, 160),
    (N'Hot Nuts 55g', '7500478004227', N'Barcel', 16.50, 155),
    (N'Leche Nido FortiGrow 360g', '7501058632610', N'Nestlé', 75.00, 45),
    (N'Polvorones 6pzas', '7501000112449', N'Marinela', 26.00, 90),
    (N'Consomé Knorr Suiza Pollo 8 cubos', '7501005110010', N'Knorr', 20.00, 150),
    (N'Jabón Escudo Antibacterial 110g', '7500435133316', 'Escudo', 19.00, 135),
    (N'Clamato 475ml', '7501059210016', N'Clamato', 26.00, 80),
    (N'Papas Adobadas 45g', '7501011115467', N'Sabritas', 17.00, 175),
    (N'Petit Suisse Fresa 6pzas', '7501020510124', N'Danone', 28.00, 95),
    (N'Pan Cero Cero Multigrano', '7501000111152', N'Bimbo', 58.00, 55),
    (N'Galletas Marías 170g', '7501007500038', N'Gamesa', 15.00, 200),
    (N'Harina de Trigo San Antonio 1kg', '7501022000070', N'San Antonio', 22.00, 85);

    -- Batch 3/5: Lácteos, Panadería, Botanas (50 items)
    INSERT INTO [dbo].[Producto] ([Nombre], [SKU], [Marca], [Precio], [Stock]) VALUES
    (N'Jabón de Lavandería Foca 500g', '7501026400030', N'Foca', 18.00, 100),
    (N'Sidral Mundet 600ml', '7501055300153', N'Mundet', 17.50, 140),
    (N'Takis Blue Heat 62g', '7500478004425', N'Barcel', 18.00, 180),
    (N'Leche Lala Deslactosada 1L', '7501020500033', N'Lala', 32.00, 85),
    (N'Gansito Black 50g', '7501000110476', N'Marinela', 19.00, 130),
    (N'Sal La Fina 1kg', '7501022000032', N'La Fina', 15.00, 110),
    (N'Toallas Húmedas Huggies 80pzas', '7501053300032', N'Huggies', 45.00, 60),
    (N'Mirinda 600ml', '7501031311347', N'Mirinda', 17.00, 135),
    (N'Runners 65g', '7500478004241', N'Barcel', 16.50, 150),
    (N'Queso Oaxaca Lala 400g', '7501020510209', N'Lala', 75.00, 50),
    (N'Galletas Oreo 6pzas', '7501007500052', N'Oreo', 18.00, 190),
    (N'Frijoles Refritos Bayos Isadora 454g', '7501019010014', N'Isadora', 20.00, 100),
    (N'Enjuague Bucal Listerine Cool Mint 250ml', '7500435133330', N'Listerine', 55.00, 55),
    (N'Monster Energy 473ml', '0070847022009', N'Monster', 42.00, 65),
    (N'Cacahuates Mafer Salados 50g', '7501001210122', N'Mafer', 14.00, 210),
    (N'Yogurt Griego Oikos Vainilla 150g', '7501020531082', N'Danone', 36.00, 75),
    (N'Croissants 2pzas', '7501000112463', N'Bimbo', 30.00, 80),
    (N'Gelatina D''Gari Fresa 120g', '7501022000056', N'D''Gari', 12.00, 150),
    (N'Pañales Huggies Ultraconfort Etapa 4 40pzas', '7501053300049', N'Huggies', 180.00, 25),
    (N'Coca-Cola Light 600ml', '7501055300085', N'Coca-Cola', 18.00, 145),
    (N'Papas Locas 50g', '7501011115481', N'Sabritas', 17.50, 160),
    (N'Leche Evaporada Carnation 360g', '7501058619635', N'Nestlé', 25.00, 90),
    (N'Príncipe 3pzas', '7501000110520', N'Marinela', 17.00, 170),
    (N'Aceitunas Serpis con Hueso 142g', '8410061010013', N'Serpis', 45.00, 45),
    (N'Crema Dental Sensodyne Rápido Alivio 50g', '7501006500018', N'Sensodyne', 70.00, 40),
    (N'Electrolit Uva 625ml', '7501125100013', N'Pisa', 30.00, 100),
    (N'Churritos de Maíz 60g', '7501011115504', N'Bokados', 15.00, 180),
    (N'Queso Cottage Lala 200g', '7501020510223', N'Lala', 28.00, 70),
    (N'Salsa Catsup Del Monte 320g', '7501017000114', N'Del Monte', 22.00, 95),
    (N'Limpiador multiusos Pinol 1L', '7501021100035', N'Pinol', 26.00, 95),
    (N'7 Up 600ml', '7501031311361', N'7 Up', 17.50, 130),
    (N'Fritos Chorizo y Chipotle 57g', '7501011115528', N'Sabritas', 16.50, 155),
    (N'Flan Lala Vainilla 100g', '7501020510247', N'Lala', 9.00, 160),
    (N'Pan Multigrano Linaza', '7501000111176', N'Bimbo', 60.00, 50),
    (N'Champiñones Herdez Enteros 185g', '7501003100038', N'Herdez', 28.00, 75),
    (N'Protector Solar Nivea Sun FPS 50 125ml', '4005808821454', N'Nivea', 150.00, 30),
    (N'Topo Chico Agua Mineral 600ml', '7501055301792', N'Topo Chico', 19.00, 120),
    (N'Big Mix Extra Queso 50g', '7500478004265', N'Barcel', 17.00, 140),
    (N'Leche Condensada La Lechera 387g', '7501058619659', N'Nestlé', 30.00, 80),
    (N'Pay de Nuez 1pza', '7501000112487', N'Marinela', 25.00, 90),
    (N'Mole Doña María 235g', '7501003100052', N'Doña María', 40.00, 65),
    (N'Tinte para Cabello Koleston Rubio Cenizo', '7500435133354', N'Koleston', 75.00, 40),
    (N'Del Valle Manzana 600ml', '7501055301815', N'Del Valle', 18.00, 125),
    (N'Chips Fuego 50g', '7500478004289', N'Barcel', 17.00, 150),
    (N'Crema Alpura Media 250ml', '7501055900031', N'Alpura', 20.00, 95),
    (N'Nito 62g', '7501000110544', N'Bimbo', 18.00, 160),
    (N'Galletas Saladitas 147g', '7501007500090', N'Gamesa', 16.00, 190),
    (N'Cereal Choco Krispis 220g', '7501007500113', N'Kellogg''s', 45.00, 60),
    (N'Shampoo Tío Nacho Aclarante 415ml', '650240024003', N'Tío Nacho', 85.00, 45),
    (N'Sazonador Maggi Jugo 100ml', '7501058619697', N'Maggi', 25.00, 85);

    -- Batch 4/5: Higiene, Abarrotes, Refrescos (50 items)
    INSERT INTO [dbo].[Producto] ([Nombre], [SKU], [Marca], [Precio], [Stock]) VALUES
    (N'Jabón Zest Neutro 110g', '7500435133392', N'Zest', 18.50, 130),
    (N'Agua Santa María 1L', '7501058619673', N'Santa María', 16.00, 110),
    (N'Tostitos Xtra Flamin'' Hot 55g', '7501011115542', N'Tostitos', 18.00, 170),
    (N'Leche Alpura Deslactosada 1L', '7501055900055', N'Alpura', 33.00, 80),
    (N'Canelitas 8pzas', '7501000110568', N'Marinela', 17.50, 150),
    (N'Vinagre Blanco Barrilito 1L', '7501003100076', N'Barrilito', 14.00, 90),
    (N'Suavitel Cuidado Superior 850ml', '7509546050759', N'Suavitel', 32.00, 85),
    (N'Arizona Té Verde 680ml', '0799736001000', N'Arizona', 22.00, 100),
    (N'Fritos Limón y Sal 57g', '7501011115566', N'Sabritas', 16.50, 160),
    (N'Yoplait Fresa 1kg', '7501004700017', N'Yoplait', 55.00, 55),
    (N'Galletas Habaneras Integrales 135g', '7501007500137', N'Gamesa', 18.00, 140),
    (N'Elote Dorado Herdez 220g', '7501003100090', N'Herdez', 16.00, 120),
    (N'Cotonetes Curity 100pzas', '7501053300056', N'Curity', 30.00, 70),
    (N'Vita Water Jamaica 1L', '7501055301839', N'Bonafont', 20.00, 110),
    (N'Totis Donitas Limón y Sal 100g', '7501032300019', N'Totis', 12.00, 250),
    (N'Leche de Soya Ades Original 946ml', '7501001500018', N'Ades', 38.00, 60),
    (N'Triki-Trakes 6pzas', '7501000110582', N'Marinela', 18.50, 145),
    (N'Salsa Valentina Etiqueta Negra 370ml', '7501053900023', N'Valentina', 17.00, 110),
    (N'Shampoo Head & Shoulders Limpieza Renovadora 180ml', '7500435136553', N'H&S', 45.00, 65),
    (N'Coca-Cola Café 235ml', '7501055301853', N'Coca-Cola', 20.00, 80),
    (N'Crujitos 52g', '7501011115580', N'Sabritas', 16.00, 175),
    (N'Danette Vainilla 100g', '7501020531105', N'Danone', 10.00, 150),
    (N'Muffin con Chispas de Chocolate', '7501000112500', N'Bimbo', 22.00, 100),
    (N'Caldo de Tomate Knorr 8 cubos', '7501005110034', N'Knorr', 20.00, 140),
    (N'Toallitas desinfectantes Lysol 35pzas', '7501053300070', N'Lysol', 60.00, 50),
    (N'Fuze Tea Té Negro Durazno 600ml', '7501055301877', N'Fuze Tea', 19.00, 120),
    (N'Doritos Dinamita 62g', '7500478004302', N'Sabritas', 17.50, 160),
    (N'Yogurt Activia Natural sin Azúcar 125g', '7501020531129', N'Danone', 12.00, 130),
    (N'Galletas Emperador Chocolate 10pzas', '7501007500151', N'Gamesa', 19.00, 180),
    (N'Crema Dental Crest Pro-Salud 75ml', '7500435133415', N'Crest', 35.00, 80),
    (N'Salvo Limón Líquido 750ml', '7500435133439', N'Salvo', 45.00, 75),
    (N'Squirt 600ml', '7501031311385', N'Squirt', 17.00, 135),
    (N'Onditas 50g', '7501011115603', N'Sabritas', 16.00, 165),
    (N'Leche Nutri Leche 1L', '7501020500077', N'Nutri', 22.00, 100),
    (N'Rebanadas 8pzas', '7501000110605', 'Marinela', 20.00, 120),
    (N'Atún Tuny en Aceite 140g', '7501045400016', N'Tuny', 22.00, 90),
    (N'Ariel Doble Poder Líquido 1.2L', '7500435136577', N'Ariel', 80.00, 45),
    (N'Amstel Ultra 355ml', '7503024730018', N'Amstel', 25.00, 110),
    (N'Ruffles Mega Crunch Jalapeño 48g', '7501011105048', N'Sabritas', 17.50, 150),
    (N'Jugo Activia Fresa-Plátano 240g', '7501020531143', N'Danone', 15.00, 125),
    (N'Galletas Crackets 133g', '7501007500175', N'Gamesa', 16.50, 155),
    (N'Cera para cabello Moco de Gorila 110g', '7506195000039', N'Moco de Gorila', 40.00, 70),
    (N'Dr Pepper 600ml', '7501031311408', N'Dr Pepper', 18.00, 130),
    (N'Churritos de Nopal 50g', '7501011115627', N'Susalia', 20.00, 100),
    (N'Yogurt Vitalínea Toronja 125g', '7501020531167', N'Danone', 13.00, 120),
    (N'Panquecitos con Gotas de Chocolate', '7501000112524', N'Bimbo', 24.00, 110),
    (N'Cereal Froot Loops 200g', '7501007500199', N'Kellogg''s', 45.00, 65),
    (N'Herbal Essences Acondicionador Hidratado 300ml', '7500435137291', N'Herbal Essences', 60.00, 55),
    (N'Corona Extra 355ml', '7501064191040', N'Corona', 22.00, 150),
    (N'Veladora Ecológica 1pza', '7501026400054', N'La Fina', 20.00, 80);

    -- Batch 5/5: Panadería, Lácteos, Botanas (50 items)
    INSERT INTO [dbo].[Producto] ([Nombre], [SKU], [Marca], [Precio], [Stock]) VALUES
    (N'Canada Dry Ginger Ale 600ml', '7501031311422', N'Canada Dry', 18.50, 125),
    (N'Kranky 50g', '7501000110629', N'Ricolino', 15.00, 190),
    (N'Leche Lala Light 1L', '7501020500091', N'Lala', 32.00, 80),
    (N'Mamut 2pzas', '7501007500212', N'Gamesa', 15.00, 170),
    (N'Harina para Hot Cakes Pronto 350g', '7501003100113', N'Pronto', 35.00, 70),
    (N'Bolsas para Basura Reynolds 20pzas', '7501021100059', N'Reynolds', 40.00, 60),
    (N'Lipton Té Verde Cítricos 600ml', '7501031311446', N'Lipton', 19.50, 115),
    (N'Sunchos 50g', '7501011115641', N'Sabritas', 16.00, 160),
    (N'Danup Fresa 240g', '7501020531181', N'Danone', 14.00, 140),
    (N'Galletas Chokis 6pzas', '7501007500236', N'Gamesa', 19.50, 175),
    (N'Salsa Inglesa Crosse & Blackwell 145ml', '7501058619710', N'C&B', 30.00, 80),
    (N'Bic Rastrillo 2 hojas 5 pzas', '3086120000018', N'Bic', 35.00, 90),
    (N'Michelob Ultra 355ml', '7503024730032', N'Michelob', 28.00, 100),
    (N'Churritos de Amaranto 50g', '7501011115665', N'Nopalia', 22.00, 90),
    (N'Chamito Fresa 8pzas', '7501058632634', N'Nestlé', 30.00, 85),
    (N'Bisquets 6pzas', '7501000112548', N'Bimbo', 40.00, 70),
    (N'Mayonesa Hellmann''s Clásica 190g', '7506306210058', N'Hellmann''s', 28.00, 85),
    (N'Quezas 50g', '7500478004326', N'Barcel', 17.00, 140),
    (N'Leche Alpura Selecta Entera 1L', '7501055900079', N'Alpura', 35.00, 75),
    (N'Paleta Payaso 1pza', '7501000110643', N'Ricolino', 18.00, 200),
    (N'Salsa Botanera Clásica 370ml', '7501053900030', N'La Botanera', 15.00, 120),
    (N'Pilón para pañales Bio-baby 1pza', '7501053300094', N'Bio-baby', 200.00, 20),
    (N'Victoria 355ml', '7501064191064', N'Victoria', 21.00, 145),
    (N'Fritos de la Abuela 50g', '7501011115689', N'Sabritas', 16.50, 150),
    (N'Yogurt bebible Yoplait Doble Proteína Fresa 220g', '7501004700031', N'Yoplait', 18.00, 110),
    (N'Galletas Florentinas Cajeta 4pzas', '7501007500250', N'Gamesa', 18.00, 130),
    (N'Café Taster''s Choice Descafeinado 42g', '7501058619734', N'Nescafé', 45.00, 60),
    (N'Jabón corporal Dove Blanco 100g', '7506306210072', N'Dove', 25.00, 120),
    (N'Heineken 355ml', '7503024730056', N'Heineken', 26.00, 105),
    (N'Bubulubu 2pzas', '7501000110667', N'Ricolino', 14.00, 220),
    (N'Mantequilla sin sal Lala 90g', '7501020510261', N'Lala', 24.00, 90),
    (N'Pan tostado Doble Fibra', '7501000111442', N'Bimbo', 42.00, 65),
    (N'Chiles Jalapeños en Escabeche Clemente Jacques 220g', '7501017000138', N'Clemente Jacques', 17.00, 110),
    (N'Axe Desodorante en Barra Apollo 50g', '7506195000053', N'Axe', 70.00, 50),
    (N'Indio 355ml', '7501064191088', N'Indio', 20.00, 140),
    (N'Panditas Clásicos 50g', '7501000110681', 'Ricolino', 13.00, 230),
    (N'Yogurt griego Chobani Fresa 150g', '0894700011113', N'Chobani', 38.00, 70),
    (N'Galletas Surtido Rico 234g', '7501007500274', N'Gamesa', 30.00, 95),
    (N'Crema de cacahuate Aladino 200g', '7501022000094', N'Aladino', 50.00, 60),
    (N'Rexona Clinical Expert en Barra 48g', '7506306210096', N'Rexona', 80.00, 40),
    (N'Tecate Light 355ml', '7503024730070', N'Tecate', 20.00, 130),
    (N'Duvalín Fresa-Vainilla 1pza', '7501000110704', N'Ricolino', 5.00, 300),
    (N'Queso Manchego Caperucita 200g', '7501040000063', N'Caperucita', 55.00, 55),
    (N'Muffin de Elote 1pza', '7501000112562', N'Bimbo', 23.00, 95),
    (N'Mazapán de la Rosa 28g', '7501001210146', N'De la Rosa', 6.00, 400),
    (N'Cereal Corn Flakes 250g', '7501007500304', N'Kellogg''s', 40.00, 70),
    (N'Pañuelos Kleenex Caja con 90', '7501053300117', N'Kleenex', 25.00, 100),
    (N'Enjuague Bucal Oral-B Menta Suave 250ml', '7506195000046', N'Oral-B', 40.00, 70);

    -- 3. FINALIZATION AND VERIFICATION
    -- Reseed the identity counter to the last inserted value to keep it synchronized.
    DBCC CHECKIDENT ('[dbo].[Producto]', RESEED, 250);

    COMMIT TRANSACTION;
    PRINT 'Transacción completada. 250 productos han sido registrados exitosamente en [dbo].[Producto].';

END TRY
BEGIN CATCH
    -- If an error occurs, roll back the entire transaction.
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    -- Rethrow the error to the client.
    DECLARE @ErrorMessage NVARCHAR(4000);
    DECLARE @ErrorSeverity INT;
    DECLARE @ErrorState INT;

    SELECT 
        @ErrorMessage = ERROR_MESSAGE(),
        @ErrorSeverity = ERROR_SEVERITY(),
        @ErrorState = ERROR_STATE();

    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
    PRINT 'Error durante la ejecución. La transacción ha sido revertida.';
END CATCH;
GO
